import Foundation

/// YAFDA's take on Wispr Flow's "Voice Profile": a persona derived from the
/// user's actual dictations — what they talk about and how they phrase it —
/// generated by the on-device model and refreshed as usage grows.
struct VoiceProfile: Codable, Equatable {
    var title: String
    var summary: String
    /// Total dictated words when this profile was generated; used to decide
    /// when enough new material justifies a refresh.
    var wordCountAtGeneration: Int
}

enum VoiceProfileStore {
    private static let key = "voiceProfile"
    /// Regenerate after this many new words have been dictated.
    static let refreshThreshold = 250
    /// Minimum material before the first profile.
    static let minimumWords = 80

    static func load() -> VoiceProfile? {
        guard let data = UserDefaults.standard.data(forKey: key),
              let profile = try? JSONDecoder().decode(VoiceProfile.self, from: data)
        else { return nil }
        return profile
    }

    static func save(_ profile: VoiceProfile) {
        if let data = try? JSONEncoder().encode(profile) {
            UserDefaults.standard.set(data, forKey: key)
        }
    }

    static func shouldRefresh(totalWords: Int) -> Bool {
        guard totalWords >= minimumWords else { return false }
        guard let existing = load() else { return true }
        return totalWords - existing.wordCountAtGeneration >= refreshThreshold
    }

    /// Builds the persona from recent transcripts using the on-device model.
    static func generate(
        from entries: [HistoryEntry],
        totalWords: Int,
        engine: RewriteEngine) async -> VoiceProfile? {
        guard engine.isAvailable else { return nil }

        let samples = entries.prefix(30).map(\.text).joined(separator: "\n")
        let clipped = String(samples.prefix(4000))
        guard !clipped.isEmpty else { return nil }

        let instructions = """
        You will receive samples of one person's dictated speech. Invent a \
        short, fun two-word persona title that captures what they talk about \
        and how they speak (examples of the format: "Design Inspector", \
        "Pipeline Poet", "Deadline Whisperer"). Then write one short sentence \
        (max 14 words) describing their dictation style. Answer in exactly \
        this format, nothing else:
        Title: <two word title>
        Style: <one sentence>
        """
        do {
            let reply = try await engine.rewrite(clipped, instructions: instructions)
            var title = ""
            var summary = ""
            for line in reply.components(separatedBy: "\n") {
                let trimmed = line.trimmingCharacters(in: .whitespaces)
                if trimmed.lowercased().hasPrefix("title:") {
                    title = String(trimmed.dropFirst(6))
                        .trimmingCharacters(in: .whitespaces)
                        .trimmingCharacters(in: CharacterSet(charactersIn: "\"“”."))
                } else if trimmed.lowercased().hasPrefix("style:") {
                    summary = String(trimmed.dropFirst(6))
                        .trimmingCharacters(in: .whitespaces)
                }
            }
            guard !title.isEmpty, title.count <= 40 else { return nil }
            let profile = VoiceProfile(
                title: title, summary: summary,
                wordCountAtGeneration: totalWords)
            save(profile)
            return profile
        } catch {
            return nil
        }
    }
}
